### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by RavenHogWarts** [somesanity/draw-io-obsidian#1]
## Issue Description
Unable to load plugin, even after manually downloading `webapp.zip` and extracting it.

![Image](https://github.com/user-attachments/assets/a45eab51-0d68-4064-8242-f0d8c6a08823)

## Console Error

```
app.js:1 Plugin failure: drawio TypeError: callSite.getFileName is not a function
    at callSiteLocation (index.js:268:23)
    at depd (index.js:109:14)
    at node_modules/router/lib/layer.js (layer.js:18:19)
    at __require (plugin:drawio:13:50)
    at node_modules/router/index.js (index.js:16:15)
    at __require (plugin:drawio:13:50)
    at node_modules/express/lib/application.js (application.js:26:14)
    at __require (plugin:drawio:13:50)
    at node_modules/express/lib/express.js (express.js:18:13)
    at __require (plugin:drawio:13:50)
    at node_modules/express/index.js (index.js:11:18)
    at __require (plugin:drawio:13:50)
    at anonymous (launchDrawioServer.ts:4:21)
    at e.<anonymous> (app.js:1:2488467)
    at app.js:1:276040
    at Object.next (app.js:1:276145)
    at a (app.js:1:274863)
    at Ds.wrapWithStackTracesImpl (plugin:advanced-debug-mode:696:2454)
    at s (plugin:advanced-debug-mode:696:2112)
```

## Environment

- OS: Win10
- Obsidian Version: 1.9.2
- Plugin List: 
  - `draw.io` 1.0.0
  - `advanced-debug-mode`: 1.7.3

## Additional Information

none

**Comment by RavenHogWarts** [comment]
Thank you for the quick fix—commit 8e1cfda works perfectly on Obsidian 1.9.2! Just a quick note for the community plugin submission: Obsidian’s review process requires excluding main.js from the repo (it should be built during submission instead), so you might want to remove it beforehand to avoid delays. Really appreciate your work on this plugin!
